### PR TITLE
fix: sub-second value parsing accurately

### LINKED ISSUE #127: `parse_hms()` cannot convert sub-second time accurately
``` r
"23:59:59.999" |> hms::parse_hms() |> as.double() |> as.character()
#> [1] "86399.9990000725"
```

<sup>Created on 2024-11-14 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

In the following section, the current date and time are used as an intermediate format as a double type, which I believe causes a loss of precision.

https://github.com/tidyverse/hms/blob/45e858517af7afd20f45aa78fcb553bd09d25681/R/parse.R#L31-L36

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #127

### CODE REVIEW

**Review by krlmlr — APPROVED** [review]
Thanks for tracking this down! Just curious, what's the rationale of removing `parse_time()`?

**Comment by eitsupi** [comment]
> what's the rationale of removing `parse_time()`?

There was no particular intent; I fixed it in the way that `parse_time()` was rewritten.

As an aside, I think this function is worth exporting in a follow-up PR.

**Comment by eitsupi** [comment]
@krlmlr Could you check this?

**Comment by krlmlr** [comment]
Thanks! The check might be prone to floating-point errors, we'll see.

**Comment by eitsupi** [comment]
Thanks for merging!

**Pull request merged**
